name: TileDB-Go with nightly libtiledb

on:
  push:
    paths:
      - '.github/workflows/nightly.yml'
      - '.github/scripts/nightly/**'
  schedule:
    - cron: "0 4 * * *" # Every night at 4 AM UTC (11 PM EST; 12 AM EDT)
  workflow_dispatch:

env:
  go: "1.18"

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:

    - uses: actions/checkout@v3
      with:
        repository: 'TileDB-Inc/TileDB-Go'
        ref: 'stefannaglee/sc-24303/tiledb-go-build-fails-after-3733'

    - name: Install Conda environment with go and nightly libtiledb
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: false
        environment-name: nightly
        extra-specs: |
          gcc
          go=${{ env.go }}
          tiledb
        channels: tiledb/label/nightlies, conda-forge

    - name: Install dependencies
      run: go get -t .

    - name: Test TileDB-Go
      run: |
        export CPATH=$CONDA_PREFIX/include
        export LIBRARY_PATH=$CONDA_PREFIX/lib
        export LD_LIBRARY_PATH=$CONDA_PREFIX/lib

        go test -v ./...

  Macos_Test:
    runs-on: macos-11
    strategy:
      matrix:
        # Will be checking following versions
        go: ["1.18"]
    steps:
    # Checks out repository
    - uses: actions/checkout@v2

    # Downloads TileDB-Core from release assets and install
    - name: Run TileDB install script
      run: ./.github/scripts/install_tiledb_macos.sh
      shell: bash

    # Following action sets up Go and uses the strategy matrix to test on
    # specific versions
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go get -t .

    # Tests TileDB-Go
    - name: Test TileDB-Go
      run: go test -v ./...

  macos:
    runs-on: macos-11
    needs: ubuntu
    steps:

    - uses: actions/checkout@v3
      with:
        repository: 'TileDB-Inc/TileDB-Go'
        ref: 'stefannaglee/sc-24303/tiledb-go-build-fails-after-3733'

    # - name: Install nightly TileDB from source
    #   run: |
    #     git clone https://github.com/TileDB-Inc/TileDB.git -b dev --depth 1
    #     cd TileDB
    #     mkdir build && cd build
    #     cmake -DTILEDB_VERBOSE=OFF -DTILEDB_S3=ON -DTILEDB_SERIALIZATION=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
    #     make -j$(sysctl -n hw.ncpu)
    #     sudo make -C tiledb install

    - name: Run TileDB install script
      run: ./.github/scripts/install_tiledb_macos.sh
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go }}

    - name: Install dependencies
      run: go get -t .

    - name: Test TileDB-Go
      run: go test -v ./...

  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: [ubuntu, macos]
    if: ( failure() || cancelled() ) && github.repository_owner == 'TileDB-Inc'
    steps:

    - uses: actions/checkout@v3
    - name: Open Issue
      env:
        GH_TOKEN: ${{ github.token }}
        TZ: "America/New_York"
      run: |
        gh issue create \
          --assignee Shelnutt2,ihnorton \
          --body "Nightly build failed in run [$GITHUB_RUN_ID]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" \
          --label "nightly-failure" \
          --title "Nightly build failed on $(date '+%A (%Y-%m-%d)')"
